#!/usr/bin/python

import sys
from api import add_to_group
from irods.session import iRODSSession

length = len(sys.argv)

if length == 3:
  add_to_group(sys.argv[1], sys.argv[2])
else:
  print "Usage: %s group-name user-name" % sys.argv[0]
